export var  Instruction = {
			"Pre-Assessment"		: "You should take this exam without any outside help so you can assess your knowledge of the course topics before you begin the course. It's likely you will get many of these questions wrong or find the test difficult, but that's the point of this assessment. Research shows that trying to solve a problem before you know how, increases the likelihood of you retaining what you've learned down the line.", 
			"TestList" 				: "It's a good idea to review your answers and compare them to the correct answers. To review, tap on the Settings icon of each detail. You can also retake the test to improve your performance score.",
			"dashboardPre1" 		: "Identify the weak areas with ",
			"dashboardPre2"			: " questions before you begin the course.",
			"dashboardChap" 		: "Study lessons, watch videos, and attempt cards, quizzes, and exercises.",
			"dashboardChap1" 		: "Study lessons and work through flashcards, exercises, and quizzes.",
			"dashboardPrac1" 		: "Prepare for the exam with ",
			"dashboardPrac2" 		: " questions in a simulated test environment.",
			"dashboardPost1"		: "Gauge your certification exam readiness with ",
			"dashboardPost2" 		: " questions.",
			"dashboardHis" 			: "Reports help gauge your progress and to focus on your weak areas.",
			"studyPlannerTitle" 	: "Track your progress and readiness including your completion date.",
			"gradedAssessmentTitle" : "Prove your mastery of each topic by completing the graded assessment.",
			"syncDataIns" 			: "Provide facility of syncing your course from the current status. ",
			"labHeading" 			: "Learn the real world skills using the performance-based labs.",
			"lastAccess" 			: "Continue with last accessed title",
			"flashcard"            	: 'Study card drills provide you with a means to memorize information such as terminology, definitions or concepts. Study the term or question on the card and recall its definition or answer. Now, flip the card to review explanation by clicking on the card or by using "Next" button in the navigation bar to assess your understanding. Grade yourself accordingly by choosing applicable options on the navigation bar.',
		};
export var  Lable = {
			"uCertify"                  : "uCertify",
			"preAssessment"             : "Pre-Assessment",
			"chapterLesson"             : "Chapters & Lessons",
			"practiceTest"              : "Practice Tests",
			"postAssessment"            : "Post-Assessment",
			"studyPlanner"              : "Study Planner",
			"progressHistory"           : "Test History",
			"specialModule"             : "Special Module",
			"linkWithInstructor"        : "Link with Instructor",
			"gradedAssessment"       	: "Graded Assessment",
			"certificateOfcompletion"   : "Certificate of Completion",
			"serachLibAlert"            : "We did not find any course based upon your search.",
			"serachLabAlert"            : "We did not find any lab based upon your search.",
			"serachGlossaryAlert"       : "Nothing is matched.",
			"offAlertTitle"             : "NO INTERNET CONNECTION",
			"offAlertMsg"               : "To access your course for the first time, please turn on your Internet connection.",
			"crnDownloadmsg"            : "We are setting up your course for offline use. Please be patient.",
			"lessonsNexercises"         : "Lessons & Exercises",
			"practice"                  : "Practice",
			"lab"                       : "Performance Based Labs",
			"finalPreparation"          : "Final Preparation",
			"TheBigDay"                 : "The Big Day",
			"removeInstructor"          : "You are already in a section. Remove this section first before adding another.",
			"dontHaveKey"               : "Don't have a section key? Please contact your instructor.",
			"syncData"                  : "Sync your course.",
			"prepEngineMsg1"            : "Get an item correct each time in",
			"prepEngineMsg2a"           : "consecutive attempts  to",
			"prepEngineMsg2b"           : "it. Your goal is to master all items.",
			"prepEngineInfo"            : "You can stop at any time and continue later.",
			"prepEngineReset"           : "You have mastered all items. Tap on reset and play again.",
			"three_consecutive_correct" : "Mastered! Well done!",
			"two_consecutive_correct"   : "Correct, twice! One more correct to go.",
			"one_correct"               : "Correct! Two more correct to go.",
			"endprepengine_alert"       : "This action will end the practice session, do you want to proceed?",
			"noCourse"                  : "Sorry, you are not licensed for any course. Please visit our Course Advisor and select a course to try for free.",
			"noTestHistoryLocal"        : "No test history found on your device. Go ahead and take a test or get a test history from the server.",
			"noTestHistory"             : "You haven't taken a test yet. Go ahead take a few tests. All your testing activities will be listed here.",
			"noAssignmentFound"         : "No assessment scheduled. Please contact your instructor.",
			"continue"                  : "CONTINUE",
			"reTake"                    : "RETAKE",
			"start"                     : "START",
			"result"                    : "RESULT",
			"assessmentNotStarted"      : "Assessments are only available during the course duration. Either the course start date has not arrived yet or the course end date has been passed.",
			"wrongDateMsg"              : "Target date should be greater than start date!",
			"startTestPrep"             : "Start Test Prep",
			"resetAndPlay"              : "You have mastered all items. Reset & Play",
			"resumeTestPrep"            : "Resume Test Prep"
		};
export var msg = {
		"firstSlide"		: "You are on the first slide.",
		"firstItem"			: "You are on the first item.",
		"lastItem"			: "You are on the last item.",
		"lastChapter" 		: "You are on the last chapter.",
		"reset"				: "Do you really want to reset?",
		"wrong"				: "Oops! Something went wrong.",
		"error"				: "Some error occurred, please retry after sometime.",
		"logout"			: "Do you want to logout?",
		"refresh"			: "Do you want to refresh your course?",
		"removeInstructor" 	: "Do you really want to remove instructor?",
		"sectionKeyCheck" 	: "Invalid section key",
		"classInactive" 	: "This class is not active. Please talk to the instructor.",
		"saved" 			: "Saved successfully!",
		"sectionKey" 		: "Please enter the section key.",
		"noSpace"			: "You have not sufficient space.",
		"courseInf"			: "Course information not found.",
		"loginFail"			: "Unable to login; something wrong!!",
		"loginOffline"		: "Sign in failed! You are offline. Please check your Internet connection",
		"loginIncorrect"	: "Sign in failed! The email or password you have entered is incorrect",
		"actionEnd"			: "This action will end your session, do you want to proceed?",
		"help"				: "Please contact to ucertify help team",
		"feature"			: "This feature is Under-Process !!",
		"offline"			: "Please check Your Internet connection !!",
		"local_history"     : "Test history available on device",
		"server_history"    : "Fetched additional test history",
		"no_history"        : "No test history on your server",
		"get_history"       : "Get complete test history from the server.",
		"data_info"         : "We highly recommend that you download course assets for better performance and offline use.  Download size is ",
		"data_size"         : " MB.  We also recommend that you use WiFi connection to download assets. ",
		"check_response"    : "Checking network connection availability and also fetching size of images, Please wait...",
		"loadingFailed"		: "Image loading failed. Please check your Internet connection.",
		"androidMsg"		: "Sorry, this question is not supported on Android",
		"check_connection"  : "Please check your network connection.",
		"cant_connection"	: "Can't Connect",
		"underDev"			: "Sorry, this question is not supported",
		"labMsg"            : "Compatible on desktop version",
		"exitApp"           : "Do you want to exit?",
		"syncAllServerData" : "Get all data from server",
		"completed"         : "Completed!!!"
	};
export var smQuestionTypeDetails = {
		"-1":{"name":"Single choice question","title":"Single choice question","icon":"icomoon_radio_checked"},
		"0":{"name":"Multiple choice question","title":"Multiple choice question","icon":"icomoon_checkbox_checked"},
		"1":{"name":"DragNDrop","title":"Drag and drop","icon":"icomoon_popout"},
		"2":{"name":"Lab","title":"Lab","icon":"icomoon_lab"},
		"3":{"name":"Simulation","title":"Simulation","icon":"icomoon_wand"},
		"4":{"name":"Hotspot","title":"Hotspot","icon":"icomoon_target_3"},
		"5":{"name":"Essay","title":"Essay","icon":"icomoon_libreoffice"},
		"6":{"name":"Choose N Reorder","title":"Choose and reorder","icon":"icomoon_menu_9"},
		"7":{"name":"Tree view","title":"Tree view","icon":"icomoon_tree_5"},
		"9":{"name":"FillInTheBlank","title":"Fill in the blank","icon":"icomoon_insert_template"},
		"13":{"name":"Terminal","title":"Terminal","icon":"icomoon_console"},
		"14":{"name":"MatchList","title":"Match list","icon":"icomoon_shuffle"},
		"15":{"name":"DragNDropExtended","title":"Drag and drop extended","icon":"icomoon_popout"},
		"16":{"name":"External module","title":"External module","icon":"icomoon_new_tab_2"},
		"17":{"name":"Lab simulation","title":"Lab simulation","icon":"icomoon_lab"},
		"18":{"name":"Relationship","title":"Relationship","icon":"icomoon_puzzle"},
		"19":{"name":"Charts","title":"Charts","icon":"icomoon_chart"},
		"20":{"name":"Mathematics","title":"Mathematics","icon":"icomoon_sigma"},
		"21":{"name":"Audio","title":"Audio","icon":"icomoon_music"},
		"22":{"name":"Web","title":"Web","icon":"icomoon_globe_3"},
		"23":{"name":"CCNA","title":"CCNA","icon":"icomoon_cisco"},
		"24":{"name":"Evalpro","title":"Evalpro","icon":"icomoon_code"},
		"25":{"name":"VirtualLab","title":"Virtual lab","icon":"icomoon_cloud_2"},
		"26":{"name":"Choose N Reorder Multi Grid","title":"Grid view","icon":"icomoon_grid_5"},
		"27":{"name":"Choice Matrix","title":"Choice matrix","icon":"icomoon_table_2"},
		"28":{"name":"Dream Machine","title":"Dream machine","icon":"icomoon_windy"},
		"30":{"name":"Slider","title":"Slider","icon":"icomoon_meter"}
	};
export var  gridView = {
		"dashboard" : {title: 'Dashboard', action: 'dashboard', icon: 'icomoon_dashboard', color:'#262262'},
		"pre"       : {title: 'Pre Assessment', action: 'testHelp', icon: 'icomoon_pre_assessment', color:'#F9A041'},
		"ebook"     : {title: 'Chapters & Lessons', action: 'ebookTOC', icon: 'icomoon_lesson', color:'#69A142'},
		"practice"  : {title: 'Practice Tests', action: 'practicetest', icon: 'icomoon_testprep_or_practice_test', color:'#029688'},
		"post"      : {title: 'Post Assessment', action: 'testHelp', icon: 'icomoon_post_assessment', color:'#4DB889'},
		"lab"       : {title: 'Lab', action: 'labDashboard', icon: 'icomoon_lesson', color:'#F2745F'},
		"linkwithI" : {title: 'Manage as instructor', action: 'linkwithinstructor', icon: 'icomoon_instructor', color:'#ce6262'},
		"library"   : {title: 'My Library', action: 'myLibrary', icon: 'icomoon_library', color:'#239ac8'},
	};
export var smHint = {
		"1" 	: "Tap the item from the bottom/right/left and then tap the appropriate “Drop/Place here” box on the top/left/right to place the selected item in the box. Now, to reset the dropped item long press on it.",
		"14-1"	: "Tap the tab and then the item in it. Now, drag the selected item from the top and release it to the matching item at the bottom. It will automatically create a run-time arrow between the items. Now, to reset the matched items, tap the cross symbol at the start of the arrow.",
		"14-2"	: "Tap the item from the bottom and then tap the appropriate item on the top to match the selected item. Now, to reset the matched items, tap the Reset icon, present at the upper-right corner of the box.",
		"9"		: "Tap the item from the bottom and then tap the appropriate blank box on the top to place the selected item in the box. Now, to reset the dropped item tap on it.",
	}

export var LockedMessage = {
	"chapter_off"         : "You are in a customized section. This content is unavailable.",
	"pass_protect"        : "Password protected.",
	"prereq_fulfill"      : "Prerequisite not fulfilled.",
	"available_when"      : "Available when you complete the previous chapter with",
	"available_when_type" : "Available when you complete the previous",
	"available_after"     : "Available after",
	"available_till"      : "Available until",
	"current_score_label" : "Your current score is",
	"with"                : "with",
	"exercise_small"      : "exercise",
	"quiz_small"          : "exercise",
	"cards_small"         : "exercise",
	"max_attempt_reached" : "You have exceeded the number of allowed attempts"
}